complexity:
  LongParameterList:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

formatting:
  MaximumLineLength:
    active: false

style:
  MaxLineLength:
    active: false
