name: "Set up Gradle"
description: "Checkout repository, configure JDK and Gradle"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Setup Java 21
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
