name: "Publish documentation"
description: "Publish public documentation to Github pages"

runs:
  using: "composite"
  steps:
    # expects the setup-gradle action to have run
    - name: Build documentation
      run: ./gradlew build

    - name: Upload documentation artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./spockk-docs/build/docs/
        name: spockk-docs

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: spockk-docs
