name: "Publish to Maven Central"
description: "Publish given module to Maven Central"

inputs:
  module:
    required: true
    description: "Name of the Gradle module to publish to Maven Central"
  mavenCentralUsername:
    required: true
    description: "Username specified in the User Token"
  mavenCentralPassword:
    required: true
    description: "Password specified in the User Token"
  signingInMemoryKeyId:
    required: true
    description: "ID of the signing key"
  signingInMemoryKey:
    required: true
    description: "In memory signing key"
  signingInMemoryKeyPassphrase:
    required: true
    description: "Passphrase for the in memory signing key"

runs:
  using: "composite"
  steps:
    # expects the component to be built
    - name: Publish artifact to Maven Central
      shell: bash
      run: ./gradlew :${{ inputs.module }}:publishToMavenCentral
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ inputs.mavenCentralUsername }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ inputs.mavenCentralPassword }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ inputs.signingInMemoryKeyId }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ inputs.signingInMemoryKey }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ inputs.signingInMemoryKeyPassphrase }}
